#!/usr/bin/env python3
"""
Cross-version diff of AGESA-relevant modules and APCB blobs across 5 ROMED8-2T BIOSes.
Output: docs/CROSS_VERSION_DIFF.md
"""

import hashlib
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
os.chdir(ROOT)

VERSIONS = ["3.11", "3.70", "3.80", "3.90", "4.10"]
LABEL = {"3.11": "L3.11", "3.70": "P3.70", "3.80": "P3.80", "3.90": "P3.90", "4.10": "P4.10"}

MODULES = [
    "AmdNbioPcieDxe",
    "AmdNbioPciePei",
    "AmdNbioAlibDxe",
    "AmdNbioAlibZpDxe",
    "AmdNbioBaseSspDxe",
    "AmdNbioBaseGnDxe",
    "AmdNbioBaseSspPei",
    "AmdNbioBaseGnPei",
    "AmdNbioIOMMUDxe",
    "AmdNbioIOMMUSSPPei",
    "AmdNbioIOMMUGNPei",
    "AmdCpmPcieInitDxe",
    "AmdCpmPcieInitPeim",
    "AmdApcbDxeV3",
    "AmdApcbSmmV3",
    "CbsSetupDxeSSP",
    "CbsSetupDxeZP",
    "CbsSetupDxeGN",
    "CbsBaseDxeSSP",
    "CbsBaseDxeZP",
    "CbsBaseDxeGN",
    "CbsBasePeiSSP",
    "CbsBasePeiZP",
    "CbsBasePeiGN",
    "PcieInfoJudgeDxe",
    "Setup",
    "AmdPbsSetupDxe",
    "ServerMgmtSetup",
    "AmdNbioAlibDxe",
    "AmdNbioAlibZpDxe",
]
MODULES = list(dict.fromkeys(MODULES))


def sha12(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(1 << 16):
            h.update(chunk)
    return h.hexdigest()[:12]


def find_module_body(version, modname):
    """Find the largest body.bin for a module (active-volume copy)."""
    base = ROOT / f"extracted/all/P{version}/img.bin.dump"
    if not base.exists():
        return None
    candidates = []
    for p in base.rglob("body.bin"):
        if "PE32 image section" not in str(p):
            continue
        # Parent dir name is "<idx> <ModuleName>"
        parent = p.parent.parent.name
        if parent.split(" ", 1)[-1] == modname:
            try:
                size = p.stat().st_size
                if size > 4096:
                    candidates.append((size, p))
            except OSError:
                pass
    if not candidates:
        return None
    candidates.sort()
    return candidates[-1][1]


def grep_apcb_offsets(image_path, magic=b"APCB"):
    """Return all byte offsets where the magic string appears in the raw image."""
    data = open(image_path, "rb").read()
    out = []
    start = 0
    while True:
        i = data.find(magic, start)
        if i < 0:
            break
        out.append(i)
        start = i + 1
    return out


def hexdump_range(image_path, offset, length=64):
    data = open(image_path, "rb").read()[offset:offset + length]
    return " ".join(f"{b:02x}" for b in data)


def find_apcb_dirs(version):
    """Find FFS dirs that look like APCB containers."""
    base = ROOT / f"extracted/all/P{version}/img.bin.dump"
    if not base.exists():
        return []
    apcb_guids_known = {
        "F2C70C57-99A6-44A6-AC73-15F9C9DB9527": "Apob recovery",
        "0DCD9E04-5350-4A4A-8B61-B8B1FC83AB27": "ApcbBackup",
        "37B96AF6-A6E7-4D88-816B-3F3F5B66C492": "ApcbBackup-V3",
        "6C95E0A4-5BF7-4F14-9B98-DBEE6CFB6FC2": "ApcbBinary",
        "B68C6122-D75A-4D7C-A0CD-D8B4D38C6F40": "AmdApcbBinaryFile",
    }
    out = []
    for d in base.rglob("*"):
        if not d.is_dir():
            continue
        nm = d.name
        for guid, lbl in apcb_guids_known.items():
            if guid in nm:
                # Find body.bin inside
                bb = next(d.rglob("body.bin"), None)
                if bb:
                    out.append((lbl, guid, bb))
                break
    return out


def main():
    out_lines = []
    add = out_lines.append

    add("# Cross-version diff — ROMED8-2T BIOS")
    add("")
    add("**Versions diffed:** " + ", ".join(LABEL[v] for v in VERSIONS))
    add("")
    add("_Generated by `scripts/diff_versions.py`._")
    add("")

    # ---- Image-level ----
    add("## Image-level")
    add("")
    add("| Version | File | Build mtime | SHA256(12) |")
    add("|---|---|---|---|")
    import datetime
    for v in VERSIONS:
        f = ROOT / f"images/ROMD82T{v}"
        ts = datetime.datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d")
        add(f"| **{LABEL[v]}** | `ROMD82T{v}` | {ts} | `{sha12(f)}` |")
    add("")

    # ---- Module table ----
    add("## AGESA / setup module diff")
    add("")
    add(
        "Each module's PE32 body hashed and sized per version. `=` means "
        "byte-identical to the previous column. `(missing)` means the module is "
        "absent from that version."
    )
    add("")
    header = "| Module | " + " | ".join(LABEL[v] for v in VERSIONS) + " |"
    sep = "|---|" + "|".join(["---"] * len(VERSIONS)) + "|"
    add(header)
    add(sep)

    interesting_changes = []  # (modname, [(ver_from, ver_to)])

    for m in MODULES:
        cells = []
        prev_hash = None
        prev_label = None
        change_pairs = []
        for v in VERSIONS:
            body = find_module_body(v, m)
            if body is None:
                cells.append("(missing)")
                prev_hash = None
                prev_label = LABEL[v]
                continue
            h = sha12(body)
            sz = body.stat().st_size
            if h == prev_hash:
                cells.append(f"= ({sz} B)")
            else:
                cells.append(f"`{h}` ({sz} B)")
                if prev_hash is not None:
                    change_pairs.append((prev_label, LABEL[v]))
                prev_hash = h
                prev_label = LABEL[v]
        add(f"| `{m}` | " + " | ".join(cells) + " |")
        if change_pairs:
            interesting_changes.append((m, change_pairs))

    add("")
    add("### Modules that changed across versions")
    add("")
    if not interesting_changes:
        add("- (none)")
    else:
        for m, pairs in interesting_changes:
            add(f"- **`{m}`** changed: " + ", ".join(f"{a}→{b}" for a, b in pairs))
    add("")

    # ---- APCB FFS containers ----
    add("## APCB FFS containers (by known AMD APCB GUIDs)")
    add("")
    found_any = False
    for v in VERSIONS:
        rows = find_apcb_dirs(v)
        if rows:
            found_any = True
            add(f"### {LABEL[v]}")
            add("")
            add("| Label | GUID | size | sha256(12) |")
            add("|---|---|---|---|")
            for lbl, guid, bb in rows:
                add(f"| {lbl} | `{guid}` | {bb.stat().st_size} | `{sha12(bb)}` |")
            add("")
    if not found_any:
        add("None of the standard AMD APCB GUIDs were found in any version. APCB is stored elsewhere (PSP firmware region or ASRock-custom FFS GUID).")
        add("")

    # ---- Raw 'APCB' magic scan ----
    add("## Raw `APCB` magic-byte scan")
    add("")
    add(
        "ASCII bytes `APCB` (0x41 0x50 0x43 0x42) start every APCB header. Listing all "
        "occurrences in each raw 32 MiB image. The count gives an upper-bound for how "
        "many APCB-header-bearing structures are in the image."
    )
    add("")
    add("| Version | # `APCB` occurrences | first 5 offsets (hex) |")
    add("|---|---|---|")
    apcb_offsets_per_ver = {}
    for v in VERSIONS:
        f = ROOT / f"images/ROMD82T{v}"
        offs = grep_apcb_offsets(f, b"APCB")
        apcb_offsets_per_ver[v] = offs
        first5 = ", ".join(f"`0x{o:x}`" for o in offs[:5])
        add(f"| {LABEL[v]} | {len(offs)} | {first5} |")
    add("")

    # ---- Hexdump of first few APCB headers — compare across versions ----
    add("## First 64 bytes after each APCB-magic offset (P3.70 vs P4.10)")
    add("")
    add("Compare byte-by-byte to see if the APCB structure changed between the user's BIOS and the newest public version. A diff at any non-pad position is a real change. A diff at offsets 0x10–0x1F (typical version + size + checksum bytes) is expected when content changes.")
    add("")
    for v in ["3.70", "4.10"]:
        add(f"### {LABEL[v]}")
        add("")
        add("```")
        f = ROOT / f"images/ROMD82T{v}"
        for off in apcb_offsets_per_ver[v][:5]:
            hd = hexdump_range(f, off, 64)
            add(f"@ 0x{off:08x}  {hd}")
        add("```")
        add("")

    # ---- AGESA debug strings differential — Gen4 / ESM / TargetLinkSpeed ----
    add("## AGESA Gen4/ESM string-presence comparison")
    add("")
    add(
        "Search every BIOS image for AGESA debug strings tied to PCIe Gen-cap and "
        "ESM (Gen4) logic. A change in count between versions indicates AGESA "
        "code added/removed paths. Same count + identical strings → AGESA path "
        "unchanged across that span."
    )
    add("")
    needles = [
        b"maxLinkSpeedCap",
        b"targetLinkSpeed",
        b"GEN4_EN_STRAP",
        b"ESM Training FAILED",
        b"Port does not have ESM enabled",
        b"DxioPortMapping",
        b"Setting ESM rates",
        b"Speed change to ESM gen4 was successful",
    ]
    add("| String | " + " | ".join(LABEL[v] for v in VERSIONS) + " |")
    add("|---|" + "|".join(["---"] * len(VERSIONS)) + "|")
    for needle in needles:
        cells = []
        for v in VERSIONS:
            data = open(ROOT / f"images/ROMD82T{v}", "rb").read()
            cells.append(str(data.count(needle)))
        add(f"| `{needle.decode()}` | " + " | ".join(cells) + " |")
    add("")

    # ---- Per-slot Link Speed menu presence in Setup IFR per version ----
    add("## Per-slot AMD PCIE Link Speed menu — presence by version")
    add("")
    add(
        "For each version, extract the ASRock-board `Setup` HII module, run "
        "`ifrextractor`, and count occurrences of `OneOf Prompt: \"PCIE[1-9] Link Speed\"`. "
        "Tells us whether ASRock kept the (vestigial) per-slot menu or removed it. "
        "If a version removed it, that's a strong hint ASRock realized it doesn't work."
    )
    add("")
    add("| Version | `Setup` PE32 size | per-slot Link Speed entries | per-slot Link Width entries |")
    add("|---|---|---|---|")
    import tempfile
    for v in VERSIONS:
        body = find_module_body(v, "Setup")
        if body is None:
            add(f"| {LABEL[v]} | (missing) | – | – |")
            continue
        sz = body.stat().st_size
        with tempfile.TemporaryDirectory() as td:
            tmp = Path(td) / "Setup.pe32"
            tmp.write_bytes(body.read_bytes())
            subprocess.run(["ifrextractor", str(tmp)], capture_output=True)
            txt = next(tmp.parent.glob("*.ifr.txt"), None)
            if txt is None:
                add(f"| {LABEL[v]} | {sz} B | (no IFR) | – |")
                continue
            content = txt.read_text(errors="replace")
            ls = sum(
                1
                for line in content.splitlines()
                if "Prompt:" in line and "PCIE" in line and "Link Speed" in line
            )
            lw = sum(
                1
                for line in content.splitlines()
                if "Prompt:" in line and "PCIE" in line and "Link Width" in line
            )
            add(f"| {LABEL[v]} | {sz} B | {ls} | {lw} |")
    add("")

    # Write
    out = ROOT / "docs/CROSS_VERSION_DIFF.md"
    out.write_text("\n".join(out_lines))
    print(f"Wrote {out} ({sum(len(l) for l in out_lines)} chars)")


if __name__ == "__main__":
    main()
